### ISSUE TITLE
USER STORY: Using keyboard to navigate the web app

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#10]
As a **visually impaired user**, I want to **use keyboard shortcuts** to **navigate the website, so I can easily move between sections without needing a mouse**.

## Acceptance Criteria
* CRITERIA 1

## Tasks
- [x] Add responsive top navigation  
- [x] Follow best accessibility principles to structure the html of the navbar 
- [x] Add aria-labels and aria roles to navbar
