### ISSUE TITLE
USER STORY: Semantic HTML

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#11]
As a **developer**, I want to **implement semantic HTML and ARIA roles**, so that **screen readers can accurately interpret and navigate the page content**.

## Acceptance Criteria
* Maintain a clear and simple structure to make your HTML document easy to read and understand. 
* Use semantic tags to enhance accessibility for screen readers and other assistive technologies.

## Tasks
- [x] There's an appropriate h1 tag on the page.
- [x] Headings are ordered properly.
- [x] All links go somewhere.
- [x] Images have meaningful alternative text.
- [x] Links have aria-label.
