### ISSUE TITLE
USER STORY: FAQs section

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#17]
As a **user** I would like to **see a FAQ section**, so I can **access common queries easily and self-serve.**

## Acceptance Criteria
* The FAQ has different questions that can be clicked to get the answer.

## Tasks
- [x] Create the content of the FAQ
- [x] Design the FAQ
- [x] Implement a FAQ section
- [x] #48
