### ISSUE TITLE
USER STORY: Weather forecast expands hourly

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#18]
As a **user**, I can **check today's weather by hours**, so that I **can dress accordingly**.

## Acceptance Criteria
* The user can see the evolution of the weather by hours thanks to the API.

## Tasks
- [ ] Design the weather section
- [ ] Add weather API access in the website.
- [ ] Display API information in the weather section
