### ISSUE TITLE
USER STORY: Weather Information

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#2]
As a user, I want to see current weather information for my location.

## Acceptance Criteria
* The user can access the weather of his location when opening the app.

## Tasks
- [x] Create weather widget UI component
- [x] Integrate with OpenWeatherMap or similar weather API
- [x] Implement error handling
- [x] Implement geolocation functionality

**Comment by Shiimymy** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation
