### ISSUE TITLE
USER STORY: Other plain text sources text-to-speech

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#20]
As a **user**, I want to **convert my text from other sources into speech**, so I can **read emails and other articles.**

## Acceptance Criteria
* The user can paste text in a dedicate form to convert it to speech.

## Tasks
- [ ] Create text input area
- [ ] Implement text-to-speech conversion
- [ ] Add playback controls (check volume implementation ?)

**Comment by DomoMKT** [comment]
you can find a reliable and high-quality solution for converting your text into speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com).
