### ISSUE TITLE
USER STORY: Read aloud Weather info

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#3]
As a **user with visual impairments**, I want to **hear** the **weather information read aloud**

## Acceptance Criteria
* The user can start or pause the lecture thanks to a button

## Tasks
- [x] Implement text-to-speech functionality using Web Speech API
- [x] Create speech controls (play, pause, stop) - if needed for this widget
- [x] Format weather data into readable text

**Comment by DomoMKT** [comment]
you can easily convert your desired weather information to high-quality audio with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com)!
