### ISSUE TITLE
USER STORY: Browse news articles

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#4]
As a **user**, I want to **browse** latest **news articles**

## Acceptance Criteria
* CRITERIA 1

## Tasks
- [x] Create news section layout
- [x] Integrate with a news API
- [x] Implement error handling
- [x] Implement article preview cards
- [x] Plan CSS Grid
