### ISSUE TITLE
USER STORY: Colour-blind compatible colour theme

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#6]
As a **user with visual impairments**, I want to **switch** between **different color themes**.

## Acceptance Criteria
* CRITERIA 1

## Tasks
- [x] Create colour-blind friendly themes
- [ ] Create theme switcher component
- [x] Implement high contrast theme
- [ ] Store user theme preference
